### ISSUE TITLE
Any Plans to run BYOR in Kubernetes?

### ISSUE THREAD

**Issue by arjunm183** [thoughtworks/build-your-own-radar#56] opened 2018-03-15 13:05 UTC
Hello Team,

Are there are any plans to run BYOR in Kubernetes Environment ?

Thanks and Regards,
Arjun.M

**Comment by arunvelsriram** [comment] 2018-03-15 16:39
Hi. You can run the existing Docker image `wwwthoughtworks/build-your-own-radar` on any scheduler.

**Comment by arunvelsriram** [comment] 2018-03-15 16:40
For example you can quickly create Kubernetes Deployment like this:
```
 kubectl run byor --env SERVER_NAMES=localhost --image wwwthoughtworks/build-your-own-radar
```

**Comment by arjunm183** [comment] 2018-03-19 07:28
@arunvelsriram I tried this. Deployment is done. However when i expose the service as below.

1) kubectl expose deployment byor --port=8080 --target-port=80 --type=NodePort
2) When  i open the URL it shows 403 error( Forbidden )

**Comment by arunvelsriram** [comment] 2018-03-19 08:34
That's probably due to the default server block in the nginx configuration.
https://github.com/thoughtworks/build-your-own-radar/blob/master/default.template#L5

This default server block will be removed in #48 

A simple workaround is to set the `Host` in the request header:

`curl -H 'Host: hostname' http://addr:nodeport`

**Comment by mohamednajiullah** [comment] 2018-06-21 06:17
The issue is now resolved in the latest release. We have removed the server name dependency in the nginx.conf block.

Please use the latest docker image for this.

**Closed by mohamednajiullah** 2018-06-21 06:17 UTC
