### ISSUE TITLE
Not able to generate the visualization due to CORS error

### ISSUE THREAD

**Issue by feeeeliipe** [thoughtworks/build-your-own-radar#296] opened 2023-01-20 15:05 UTC
I'm trying to generete the visualization following README instructions, but getting CORS error when executing it.

Data: https://docs.google.com/spreadsheets/d/1GBX3-jzlGkiKpYHF9RvVtu6GxSrco5OYTBv9YsOTXVg/edit#gid=0

![image](https://user-images.githubusercontent.com/41023393/213730997-0c04a1d8-32e8-4ec8-b110-01ab31702925.png)

**Comment by devansh-sharma-tw** [comment] 2023-01-30 13:52
Hi @feeeeliipe ,

The CORS error that you see is currently expected and should not be the cause of the visualization failing.
Can you please confirm if you are using the latest code or docker image to test this ?

**Comment by feeeeliipe** [comment] 2023-01-31 18:26
Hi @devansh-sharma-tw,

I'm not running it locally. I'm using it under https://radar.thoughtworks.com/ domain as described in the readme file.

**Comment by orenmazor** [comment] 2023-02-01 16:36
I'm seeing the same issue on the latest safari and firefox

**Comment by devansh-sharma-tw** [comment] 2023-02-21 13:34
Hi @feeeeliipe and @orenmazor , sorry for the delay in the reply. Are you still facing this issue on radar.thoughtworks.com ?

We've recently pushed an update that would allow using public Google Sheets without asking for a Google sign in, so if auth was the issue in this scenario it should be fixed now.

Thanks!

**Comment by orenmazor** [comment] 2023-02-21 13:43
Thanks devansh! I was eventually able to use this by turning all security features off on a safari browser.

I’ll test this out in a normal browser

**Closed** 2023-07-21 22:16 UTC
